name: Build Windows Executable

on:
  push:
    branches:
      - main # Or your main branch name, e.g., master
  pull_request:
    branches:
      - main # Or your main branch name

jobs:
  build-windows:
    runs-on: windows-latest # Use a Windows runner for Windows compilation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # This action checks out your repository code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Specify your Python version, e.g., '3.10' or '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow pyinstaller

      - name: Compile with PyInstaller
        # This assumes your divadivamodule.spec file is in the root of your repository
        run: pyinstaller divadivamodule.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: divadivamodule-windows-exe
          path: dist/divadivamodule.exe # Path to your compiled executable
          # If you ended up with a --onedir build, you'd upload the whole folder:
          # path: dist/divadivamodule/ # Example if it was a folder
